// tailwind.config.ts
import type { Config } from "tailwindcss"

const config = {
  // Uses the content paths generated by create-next-app and shadcn/ui
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
 
    
    extend: { 
      // Custom Colors Redefined to Match HTML
      colors: {
        'primary': {
          DEFAULT: '#171716', // Maverick-base (Dark Text/Background)
          foreground: '#FAFAFA', // White/Light contrast text on primary
        },
        'secondary': {
          DEFAULT: '#5AD5E2', // Primary Blue/Cyan (Target color for button/hover text)
 
          foreground: '#171716', // Dark text on secondary
          'dark-text': '#008BAD', 
        },
        'tertiary': {
          DEFAULT: '#A9D834', // Primary Green/Lime (Maverick-Accent)
          foreground: '#171716', // Dark text on tertiary
          'dark-text': '#769623', 
        },
        'form-gold': '#FFC33A', // Used for main CTA button
        'header-dark': '#1a1919', // Header background
  
        'footer-dark': '#121111', // Footer background

        // --- NEW WHATSAPP GREEN ---
        'whatsapp-green': '#25D366', 

        // Standard shadcn/ui colors (Consolidated)
        border: "hsl(var(--border))",
    
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
 
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
        
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
 
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
      },
    
      // Font Migration
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'monospace'],
      },
    
      // --- Custom Keyframes Definition (FIXED SYNTAX) ---
      keyframes: { 
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
   
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
   
        },
        // **SYNTAX CORRECTED: Ensure 'transform' is used for each %**
        "shake-logo": { 
            "0%": { transform: "translateX(0)" },
            "25%": { transform: "translateX(-3px) rotate(-2deg)" },
   
            "50%": { transform: "translateX(3px) rotate(2deg)" },
            "75%": { transform: "translateX(-3px) rotate(-2deg)" },
            // COMMA ADDED AND SYNTAX CORRECTED
            "100%": { transform: "translateX(0)" }, 
        },
        /** Idle ~4s, then a slow gentle wiggle (header paint roller) */
        "roller-wiggle-interval": {
          "0%, 78%": { transform: "rotate(0deg) translateX(0)" },
          "82%": { transform: "rotate(-6deg) translateX(-1px)" },
          "86%": { transform: "rotate(6deg) translateX(1px)" },
          "90%": { transform: "rotate(-4deg) translateX(-1px)" },
          "94%": { transform: "rotate(4deg) translateX(1px)" },
          "97%, 100%": { transform: "rotate(0deg) translateX(0)" },
        },
        "infinite-scroll": {
            from: { transform: "translateX(0)" },
            to: { transform: "translateX(-50%)" }, 
        }
      }, 
      
      // --- Custom Animation Properties Definition ---
      animation: { 
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "shake": 
 "shake-logo 1.5s ease-in-out 3", 
        "roller-wiggle-slow": "roller-wiggle-interval 5s ease-in-out infinite",
        "infinite-scroll": "infinite-scroll 25s linear infinite", 
      }, 
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config